name: Terraform GCP Deployment

on:
  push:
    branches:
      - main  # Triggers the workflow on push to the main branch

jobs:
  terraform:
    name: Setup Terraform and Deploy Resources
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Google Cloud SDK
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          credentials_file_path: ${{ secrets.GCP_CREDENTIALS }}
          
      # Set up Google Cloud credentials
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      # Configure Google Cloud project and region
      - name: Set up Google Cloud project
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud config set compute/region ${{ secrets.GCP_REGION }}
          gcloud config set compute/zone ${{ secrets.GCP_ZONE }}

      # Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0  # Specify your desired Terraform version

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Apply Terraform Plan
      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          GOOGLE_CLOUD_KEYFILE_JSON: ${{ secrets.GCP_CREDENTIALS }}
          TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}
          TF_VAR_region: ${{ secrets.GCP_REGION }}
          TF_VAR_zone: ${{ secrets.GCP_ZONE }}
          TF_VAR_ssh_username: ${{ secrets.SSH_USERNAME }}
          TF_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
