name: Terraform GCP Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main  # Trigger on PRs targeting the main branch
  workflow_dispatch:        # Manual trigger
  schedule:
    - cron: '0 0 * * 0'      # Weekly schedule (every Sunday at midnight UTC)

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with: 
          version: 'latest'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          credentials_file_path: ${{ secrets.GCP_CREDENTIALS }}

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -lock=false

  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: terraform-plan

    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request' # Prevent apply on PRs

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          credentials_file_path: ${{ secrets.GCP_CREDENTIALS }}

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve -lock=false
